# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181024_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='home_pics/'),
        ),
    ]
