# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_item_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='home_pics/'),
        ),
        migrations.AlterField(
            model_name='clean',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='home.Week'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='home_pics/'),
        ),
        migrations.AlterField(
            model_name='supper',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='home_pics/'),
        ),
    ]
